// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VideoGames.Data;

namespace VideoGames.Migrations
{
    [DbContext(typeof(GamesDbContext))]
    [Migration("20210219135032_SeedDbMigration")]
    partial class SeedDbMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VideoGames.Models.Game", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Completed")
                        .HasColumnType("bit");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = "b23b62ab-f69c-437b-9ace-4e515cb658f0",
                            Completed = true,
                            Genre = "RPG",
                            Name = "TorchLight 2"
                        },
                        new
                        {
                            Id = "4fae2c9a-6b70-4fcc-8821-e6801cc16d38",
                            Completed = false,
                            Genre = "Looter Shooter",
                            Name = "Borderlands 3"
                        },
                        new
                        {
                            Id = "9fc71bd6-bbeb-463f-88ee-aa756a7e83b8",
                            Completed = true,
                            Genre = "Shooter",
                            Name = "Gears Of War 3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
