// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VideoGames.Data;

namespace VideoGames.Migrations
{
    [DbContext(typeof(GamesDbContext))]
    [Migration("20210219140410_InititialMigration2.1")]
    partial class InititialMigration21
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VideoGames.Models.Game", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Completed")
                        .HasColumnType("bit");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = "dcbbd972-aea6-478e-a07d-8a6b328e6791",
                            Completed = false,
                            Genre = "Action",
                            Name = "Batman Arkham Asylum"
                        },
                        new
                        {
                            Id = "91f403aa-1e2e-4410-a605-b1bda1e486a9",
                            Completed = false,
                            Genre = "MMORPG",
                            Name = "Guild Wars 2"
                        },
                        new
                        {
                            Id = "092ac723-015f-4b1e-9f9d-0029786bd978",
                            Completed = true,
                            Genre = "Shooter",
                            Name = "Halo"
                        },
                        new
                        {
                            Id = "ed35547b-0f77-4001-8618-e03832558564",
                            Completed = false,
                            Genre = "Shooter",
                            Name = "Call Of Duty 2"
                        },
                        new
                        {
                            Id = "bcccb714-e036-4cd7-b02d-03c624c482a6",
                            Completed = true,
                            Genre = "Shooter",
                            Name = "BioShock Infinite"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
