// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VideoGames.Data;

namespace VideoGames.Migrations
{
    [DbContext(typeof(GamesDbContext))]
    [Migration("20210219135433_Add2MoreGames")]
    partial class Add2MoreGames
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VideoGames.Models.Game", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Completed")
                        .HasColumnType("bit");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = "e82c3ebe-56b3-4f09-a671-a93b5b79a1eb",
                            Completed = true,
                            Genre = "RPG",
                            Name = "TorchLight 2"
                        },
                        new
                        {
                            Id = "93ea35a4-f65a-4dcd-a1c7-fec3b8718d24",
                            Completed = false,
                            Genre = "Looter Shooter",
                            Name = "Borderlands 3"
                        },
                        new
                        {
                            Id = "6e506d75-9b24-4947-ae67-fb2fa541cc4f",
                            Completed = true,
                            Genre = "Shooter",
                            Name = "Gears Of War 3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
