// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VideoGames.Data;

namespace VideoGames.Migrations
{
    [DbContext(typeof(GamesDbContext))]
    partial class GamesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VideoGames.Models.Game", b =>
                {
                    b.Property<long>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Completed")
                        .HasColumnType("bit");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GameId");

                    b.ToTable("NewGames");

                    b.HasData(
                        new
                        {
                            GameId = -1L,
                            Completed = false,
                            Genre = "Action",
                            Name = "Batman Arkham Asylum"
                        },
                        new
                        {
                            GameId = -2L,
                            Completed = false,
                            Genre = "MMORPG",
                            Name = "Guild Wars 2"
                        },
                        new
                        {
                            GameId = -3L,
                            Completed = true,
                            Genre = "Shooter",
                            Name = "Halo"
                        },
                        new
                        {
                            GameId = -4L,
                            Completed = false,
                            Genre = "Shooter",
                            Name = "Call Of Duty 2"
                        },
                        new
                        {
                            GameId = -5L,
                            Completed = true,
                            Genre = "Shooter",
                            Name = "BioShock Infinite"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
